version: '3'

services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./config.cfg:/app/config.cfg
    environment:
      - PYTHONUNBUFFERED=1
    # command: uvicorn src:app --host 0.0.0.0 --port 80
